services:
  localstack:
    image: localstack/localstack:3.4
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      # - ./localstack:/var/lib/localstack"
      - /var/run/docker.sock:/var/run/docker.sock

  terraform:
    image: hashicorp/terraform:1.8
    volumes:
      - ./terraform:/app
    working_dir: /app
    entrypoint: "/bin/sh -c 'terraform init && terraform apply -auto-approve'"
    depends_on:
      localstack:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    environment:
      - POSTGRES_USER=notifications
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=notifications
    command: postgres -c log_statement=all
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notifications"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: api/gateway/Dockerfile
    environment:
      - PORT=8080
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=mock_access_key
      - AWS_SECRET_ACCESS_KEY=mock_secret_key
      - NOTIFICATIONS_TOPIC_ARN=arn:aws:sns:us-east-1:000000000000:notifications
      - POSTGRES_URL=postgres://notifications:dbpassword@postgres:5432/notifications?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      localstack:
        condition: service_healthy
      postgres:
        condition: service_healthy
      terraform:
        condition: service_completed_successfully
